#!/usr/bin/sh
# river/init
# @author nate zhou
# @since 2025,2026

# https://codeberg.org/unixchad/kwm
# https://github.com/gnuunixchad/kwm
/usr/local/bin/kwm &

# 状态栏
${HOME}/.local/bin/damblocks --fifo &
